import Head from 'next/head'

import SocialSidebar from '@/components/SocialSidebar'

import HomeScreen from '@/components/HomeScreen'
import AboutScreen from '@/components/AboutScreen'
import SkillsScreen from '@/components/SkillsScreen'
import ProjectScreen from '@/components/ProjectScreen'
import ContactScreen from '@/components/ContactScreen'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'

export default function Home() {
  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Dominik Nossal</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar />

      <HomeScreen />

      <AboutScreen />

      <SkillsScreen />

      <ProjectScreen />

      <ContactScreen />

      <Footer />

      <SocialSidebar />
    </div>
  )
}
