import Head from 'next/head'
import Navbar from '@/components/navbar'

import SocialSidebar from '@/components/SocialSidebar'

import HomeScreen from '@/components/HomeScreen'
import AboutScreen from '@/components/AboutScreen'
import ProjectScreen from '@/components/ProjectScreen'

import { useEffect, useState } from 'react'

import { Element } from 'react-scroll'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dominik Nossal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <HomeScreen />

      <AboutScreen />

      <ProjectScreen />

      <SocialSidebar />
    </div>
  )
}
